/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundVideo: typeof import('./src/components/atoms/BackgroundVideo.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    Default: typeof import('./src/components/layouts/default.vue')['default']
    FormGroup: typeof import('./src/components/molecules/FormGroup.vue')['default']
    HeroContent: typeof import('./src/components/molecules/HeroContent.vue')['default']
    HeroSection: typeof import('./src/components/organisms/HeroSection.vue')['default']
    OdontoAc: typeof import('./src/components/ui/header/OdontoAc.vue')['default']
    OdontoFooter: typeof import('./src/components/organisms/OdontoFooter.vue')['default']
    OdontoHb: typeof import('./src/components/ui/header/OdontoHb.vue')['default']
    OdontoHeader: typeof import('./src/components/organisms/OdontoHeader.vue')['default']
    OdontoHome: typeof import('./src/components/pages/OdontoHome.vue')['default']
    OdontoLogo: typeof import('./src/components/ui/header/OdontoLogo.vue')['default']
    OdontoNavBar: typeof import('./src/components/ui/header/OdontoNavBar.vue')['default']
  }
}
